// This is an automatically generated file, any changes will be overwritten on compiliation!


#ifndef EmbeddedFiles_AutoGenerated_H
#define EmbeddedFiles_AutoGenerated_H


#include "EmbeddedFiles_AutoGenerated_Blobs.h"
const char* const etag_file_default_htm = "\"073f35b0\"";
const size_t size_file_default_htm = 84945;

const char* const etag_file_echarts_min_js_gz = "\"5567c083\"";
const size_t size_file_echarts_min_js_gz = 178666;

const char* const etag_file_favicon_ico_gz = "\"ed8c743f\"";
const size_t size_file_favicon_ico_gz = 1308;

const char* const etag_file_jquery_js_gz = "\"c449175e\"";
const size_t size_file_jquery_js_gz = 30885;

const char* const etag_file_lang_de_js_gz = "\"582ba7d5\"";
const size_t size_file_lang_de_js_gz = 5853;

const char* const etag_file_lang_en_js_gz = "\"ba1dda7f\"";
const size_t size_file_lang_en_js_gz = 651;

const char* const etag_file_lang_es_js_gz = "\"bf7aea2f\"";
const size_t size_file_lang_es_js_gz = 3172;

const char* const etag_file_lang_fr_js_gz = "\"ff9e25de\"";
const size_t size_file_lang_fr_js_gz = 3875;

const char* const etag_file_lang_hr_js_gz = "\"8bbdf312\"";
const size_t size_file_lang_hr_js_gz = 3601;

const char* const etag_file_lang_nl_js_gz = "\"1941300b\"";
const size_t size_file_lang_nl_js_gz = 5267;

const char* const etag_file_lang_pt_js_gz = "\"1ec6aca7\"";
const size_t size_file_lang_pt_js_gz = 3594;

const char* const etag_file_lang_ru_js_gz = "\"01e4583a\"";
const size_t size_file_lang_ru_js_gz = 7882;

const char* const etag_file_logo_bmp = "\"402e2bec\"";
const size_t size_file_logo_bmp = 5050;

const char* const etag_file_logo_png = "\"f4ea870b\"";
const size_t size_file_logo_png = 2506;

const char* const etag_file_notify_min_js_gz = "\"2b188412\"";
const size_t size_file_notify_min_js_gz = 7459;

const char* const etag_file_pagecode_js_gz = "\"0c98b2db\"";
const size_t size_file_pagecode_js_gz = 17010;

const char* const etag_file_patron_png = "\"c25f5f8e\"";
const size_t size_file_patron_png = 1966;

const char* const etag_file_style_css_gz = "\"e688cedc\"";
const size_t size_file_style_css_gz = 2021;

const char* const etag_file_wait_png = "\"5b9c4e8c\"";
const size_t size_file_wait_png = 26018;

const char* const etag_file_warning_png = "\"05eba775\"";
const size_t size_file_warning_png = 1626;

#endif