// This is an automatically generated file, any changes will be overwritten on compiliation!


#ifndef EmbeddedFiles_AutoGenerated_H
#define EmbeddedFiles_AutoGenerated_H


#include "EmbeddedFiles_AutoGenerated_Blobs.h"
const char* const etag_file_default_htm = "\"073f35b0\"";
const size_t size_file_default_htm = 84945;

const char* const etag_file_echarts_min_js_gz = "\"dbaf1a26\"";
const size_t size_file_echarts_min_js_gz = 178666;

const char* const etag_file_favicon_ico_gz = "\"d807d3a1\"";
const size_t size_file_favicon_ico_gz = 1308;

const char* const etag_file_jquery_js_gz = "\"8d08223f\"";
const size_t size_file_jquery_js_gz = 30885;

const char* const etag_file_lang_de_js_gz = "\"6c67602f\"";
const size_t size_file_lang_de_js_gz = 5853;

const char* const etag_file_lang_en_js_gz = "\"c8567cbb\"";
const size_t size_file_lang_en_js_gz = 651;

const char* const etag_file_lang_es_js_gz = "\"54cedf4c\"";
const size_t size_file_lang_es_js_gz = 3172;

const char* const etag_file_lang_fr_js_gz = "\"1dadc0ad\"";
const size_t size_file_lang_fr_js_gz = 3875;

const char* const etag_file_lang_hr_js_gz = "\"0676bfa7\"";
const size_t size_file_lang_hr_js_gz = 3601;

const char* const etag_file_lang_nl_js_gz = "\"1b022c84\"";
const size_t size_file_lang_nl_js_gz = 5267;

const char* const etag_file_lang_pt_js_gz = "\"8a233acc\"";
const size_t size_file_lang_pt_js_gz = 3594;

const char* const etag_file_lang_ru_js_gz = "\"40adf1c9\"";
const size_t size_file_lang_ru_js_gz = 7882;

const char* const etag_file_logo_bmp = "\"ef05b504\"";
const size_t size_file_logo_bmp = 5050;

const char* const etag_file_logo_png = "\"ba6412cf\"";
const size_t size_file_logo_png = 2506;

const char* const etag_file_notify_min_js_gz = "\"6723d0e7\"";
const size_t size_file_notify_min_js_gz = 7459;

const char* const etag_file_pagecode_js_gz = "\"005e3c45\"";
const size_t size_file_pagecode_js_gz = 17010;

const char* const etag_file_patron_png = "\"34b6d0db\"";
const size_t size_file_patron_png = 1966;

const char* const etag_file_style_css_gz = "\"57d56b6d\"";
const size_t size_file_style_css_gz = 2021;

const char* const etag_file_wait_png = "\"bf81baf6\"";
const size_t size_file_wait_png = 26018;

const char* const etag_file_warning_png = "\"431e4455\"";
const size_t size_file_warning_png = 1626;

#endif